import { BankLists } from "@/types/bankLists";

export const bankLists: BankLists[] = [
    {
        type: "",
        name: "ทรูมันนี่วอเล็ต",
        image: "/image/wallet.png",
        alt: "truemoney",
        code: "999",
        validate: [10],
        gradient: "from-orange-400 to-orange-600",
    },
    {
        type: "",
        name: "ธนาคารกสิกรไทย",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/kbank.png",
        alt: "kbank",
        code: "004",
        validate: [10],
        gradient: "from-green-400 to-green-600",
    },
    {
        type: "",
        name: "ธนาคารไทยพาณิชย์",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/scb.png",
        alt: "scb",
        code: "014",
        validate: [10],
        gradient: "from-purple-400 to-purple-600",
    },
    {
        type: "",
        name: "ธนาคารออมสิน",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/gsb.png",
        alt: "gsb",
        code: "030",
        validate: [10, 11, 12, 13, 14, 15],
        gradient: "from-pink-400 to-pink-600",
    },
    {
        type: "",
        name: "ธนาคารกรุงเทพ",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/bbl.png",
        alt: "bbl",
        code: "002",
        validate: [10],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารกรุงไทย",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/ktb.png",
        alt: "ktb",
        code: "006",
        validate: [10],
        gradient: "from-sky-400 to-sky-600",
    },
    {
        type: "",
        name: "ธนาคารยูโอบี",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/uob.png",
        alt: "uob",
        code: "024",
        validate: [10],
        gradient: "from-indigo-400 to-indigo-600",
    },
    {
        type: "",
        name: "ธนาคารอาคารสงเคราะห์",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/ghb.png",
        alt: "ghb",
        code: "033",
        validate: [12],
        gradient: "from-orange-400 to-orange-600",
    },
    {
        type: "",
        name: "ธนาคารซูมิโตโม มิตซุย ทรัสต์",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/smbc.png",
        alt: "smbc",
        code: "018",
        validate: [10],
        gradient: "from-green-400 to-green-600",
    },
    {
        type: "",
        name: "ธนาคารแห่งประเทศจีน",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/china.png",
        alt: "china",
        code: "052",
        validate: [10, 11, 12, 13, 14, 15],
        gradient: "from-red-400 to-red-600",
    },
    {
        type: "",
        name: "ธนาคารไทยเครดิต เพื่อรายย่อย",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/tcrb.png",
        alt: "tcrb",
        code: "071",
        validate: [10],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารไอซีบีซี (ไทย)",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/icbc.png",
        alt: "icbc",
        code: "070",
        validate: [10],
        gradient: "from-red-400 to-red-600",
    },
    {
        type: "LHBYOU",
        name: "ธนาคารแลนด์ แอนด์ เฮ้าส์",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/lhb.png",
        alt: "lhb",
        code: "073",
        validate: [10],
        gradient: "from-yellow-400 to-yellow-600",
    },
    {
        type: "",
        name: "ธนาคารเกียรตินาคินภัทร",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/kkpfg.png",
        alt: "kkpfg",
        code: "069",
        validate: [10, 11, 12, 13, 14],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารทิสโก้",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/tisco.png",
        alt: "tisco",
        code: "067",
        validate: [14],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารกรุงศรีอยุธยา",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/bay.png",
        alt: "bay",
        code: "025",
        validate: [10],
        gradient: "from-yellow-400 to-yellow-600",
    },
    {
        type: "",
        name: "ธนาคารสแตนดาร์ดชาร์เตอร์ด (ไทย)",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/sc.png",
        alt: "sc",
        code: "020",
        validate: [10, 11],
        gradient: "from-green-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารซีไอเอ็มบี ไทย",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/cimb.png",
        alt: "cimb",
        code: "022",
        validate: [10],
        gradient: "from-red-400 to-red-600",
    },
    {
        type: "",
        name: "ธนาคารทหารไทยธนชาต",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/ttb.png",
        alt: "ttb",
        code: "011",
        validate: [10],
        gradient: "from-orange-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารมิซูโฮ",
        image: "https://d1h28837i689xj.cloudfront.net/assets/bank/mizuho.png",
        alt: "mizuho",
        code: "039",
        validate: [10],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารซิตี้แบงก์",
        image: "https://d1h28837i689xj.cloudfront.net/play/dnm42iow98zopunvg38znmkykahspl6.webp",
        alt: "citi",
        code: "017",
        validate: [10, 11, 12, 13, 14, 15],
        gradient: "from-blue-400 to-blue-600",
    },
    {
        type: "",
        name: "ธนาคารเพื่อการเกษตรและสหกรณ์การเกษตร",
        image: "https://d1h28837i689xj.cloudfront.net/play/lficnomlbmqeipzdj905404ppuy37y6.webp",
        alt: "baac",
        code: "059",
        validate: [12],
        gradient: "from-green-400 to-green-600",
    },
    {
        type: "",
        name: "ธนาคารอิสลาม",
        image: "https://d1h28837i689xj.cloudfront.net/play/cpirkhcgl6a9nq2p8ict4k5j5zo0ca2.webp",
        alt: "isbt",
        code: "066",
        validate: [10, 11, 12, 13, 14, 15],
        gradient: "from-green-400 to-green-600",
    },
    {
        type: "",
        name: "ธนาคารบีเอ็นพี พารีบาส์",
        image: "https://d1h28837i689xj.cloudfront.net/play/akfdotyypfbsb5xw3xgirf4f5q6xiv2.webp",
        alt: "bnp",
        code: "045",
        validate: [10, 11, 12, 13, 14, 15],
        gradient: "from-green-400 to-blue-600",
    },
];
