import type { Metadata, ResolvingMetadata } from "next";
import { Kanit } from "next/font/google";
import "@/styles/globals.css";
import RootLayoutTokio from "@/components/layout/RootLayoutTokio";
import { getSettingMeta, getSOS } from "@/services/setting/server";
import { redirect, RedirectType } from "next/navigation";

const kanit = Kanit({
    variable: "--font-kanit",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const dynamic = "force-dynamic";

export async function generateMetadata(): Promise<Metadata> {
    try {
        const jsonx = await getSettingMeta();
        return {
            title: jsonx.data.general.title,
            description: jsonx.data.general.description,
            keywords: jsonx.data.general.keyword,
            icons: {
                icon: jsonx.data.general.img,
                apple: jsonx.data.general.img,
            },
        };
    } catch (error) {
        return {
            title: "Create Next App",
            description: "Generated by create next app",
        }
    }
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const meta = await getSettingMeta();
    const SOS = await getSOS();
    if (SOS.data.status) {
        redirect(SOS.data.to, RedirectType.replace);
    }

    const color_shades = meta.data.general.color_shades


    return (
        <html lang="th">
            <head>
                <style>
                    {`
                        :root {
                            --background: ${color_shades.color4};
                            --main-color: ${color_shades.color7};
                            --navbar-color: ${color_shades.color4};
                            --sidebar-color: ${color_shades.color4};
                            --btn1-color: ${color_shades.color1};
                            --btn2-color: ${color_shades.color2};
                            --text-color: ${color_shades.color6};
                        }
                    `}
                </style>
                <link
                    rel="stylesheet"
                    href="https://kit-pro.fontawesome.com/releases/v7.0.0/css/pro.min.css"
                />
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            </head>
            <body
                className={`${kanit.variable} dark antialiased min-h-screen`}
            >
                <RootLayoutTokio>
                    {children}
                </RootLayoutTokio>
            </body>
        </html>
    );
}
